"""
Tests for the AI Health & RUL pipeline.

The fixture (tests/fixtures/sim_episodes.csv) was generated by training/generate_dataset.mjs
with a different seed from the training data, so these tests score unseen simulator runs.
"""

import unittest
from collections import defaultdict
from pathlib import Path

import pandas as pd

from ai_health_rul.services.health_rul_service import HealthRulService
from ai_health_rul.preprocessing.feature_engineering import GoldenTwin
from ai_health_rul.preprocessing.validation import DataQualityGuard

FIXTURE = Path(__file__).parent / "fixtures" / "sim_episodes.csv"
from ai_health_rul.config.config import SCALAR_CHANNELS as SCALAR  # noqa: E402  (all channels, as the gateway sends)
CSV_COL = {"inj_pw": "inj_pw_ms", "fuel_trim": "fuel_trim_pct", "battery_current": "battery_current_a",
           "battery_soc": "battery_soc_pct", "ambient_pressure": "ambient_pressure_bar", "oat": "oat_c"}


def frames(ep_df):
    """Yield (payload, truth_label, fault_severity, engine_severity) as the gateway sends them."""
    t = 0.0
    for _, r in ep_df.iterrows():
        t += float(r["dt_s"])
        payload = {c: float(r[CSV_COL.get(c, c)]) for c in SCALAR}
        payload["egt"] = [float(r[f"egt{i}"]) for i in range(1, 5)]
        payload["cht"] = [float(r[f"cht{i}"]) for i in range(1, 5)]
        payload["sim_time_s"] = t
        yield payload, r["label"], float(r["severity"]), float(r["engine_severity"])


class TestAiHealthRulModule(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.df = pd.read_csv(FIXTURE)
        cls.episodes = {e: g for e, g in cls.df.groupby("episode")}

    @classmethod
    def fault_runs(cls):
        """All fault episodes scored once (shared by several tests): {episode: [(result, label, sev, eng_sev)]}"""
        if not hasattr(cls, "_fault_runs"):
            cls._fault_runs = {ep: cls.run_episode(cls, HealthRulService(), ep)
                               for ep in cls.df.loc[cls.df["fault_class"] != "NONE", "episode"].unique()}
        return cls._fault_runs

    def run_episode(self, service, ep, uav="T", mutate=None, **extra):
        out = []
        for i, (payload, label, sev, eng) in enumerate(frames(self.episodes[ep])):
            payload.update(uav_id=uav, **extra)
            if mutate:
                mutate(i, payload)
            out.append((service.predict(payload), label, sev, eng))
        return out

    # ---------------- leakage regression tests ----------------
    def test_health_index_input_is_ignored(self):
        """Health is an output: a health_index in the payload must not change any result."""
        ep = self.df.loc[self.df["fault_class"] == "BLOW_BY", "episode"].iloc[0]
        a = self.run_episode(HealthRulService(), ep, health_index=0.99)
        b = self.run_episode(HealthRulService(), ep, health_index=0.05)
        for ra, rb in zip(a, b):
            self.assertEqual(ra[0].health.diagnosed_fault, rb[0].health.diagnosed_fault)
            self.assertEqual(ra[0].rul.healthIndexScore, rb[0].rul.healthIndexScore)
            self.assertEqual(ra[0].rul.rulHours, rb[0].rul.rulHours)
            self.assertEqual(ra[0].health.anomaly_score, rb[0].health.anomaly_score)

    def test_fault_label_input_is_ignored(self):
        """An injected-fault label sent by a client must not influence the diagnosis."""
        ep = self.df.loc[self.df["fault_class"] == "NONE", "episode"].iloc[0]
        a = self.run_episode(HealthRulService(), ep)
        b = self.run_episode(HealthRulService(), ep, activeFault="CYL3_INJECTOR", diagnosed_fault="CYL3_INJECTOR")
        self.assertEqual([x[0].health.diagnosed_fault for x in a], [x[0].health.diagnosed_fault for x in b])

    def test_sessions_are_isolated_per_uav(self):
        """One vehicle's fault history must not change another vehicle's prediction."""
        nom_ep = self.df.loc[self.df["fault_class"] == "NONE", "episode"].iloc[0]
        fault_ep = self.df.loc[self.df["fault_class"] == "OIL_PUMP_CAVITATION", "episode"].iloc[0]
        clean = self.run_episode(HealthRulService(), nom_ep, uav="B")
        svc = HealthRulService()
        self.run_episode(svc, fault_ep, uav="A")
        mixed = self.run_episode(svc, nom_ep, uav="B")
        self.assertEqual([x[0].rul.rulHours for x in clean], [x[0].rul.rulHours for x in mixed])

    # ---------------- behaviour on unseen simulator episodes ----------------
    def test_nominal_episodes_stay_nominal(self):
        """Includes loiter, fixed operating points and rapid throttle transitions."""
        total = flagged = 0
        for ep in self.df.loc[self.df["fault_class"] == "NONE", "episode"].unique():
            for r, *_ in self.run_episode(HealthRulService(), ep):
                total += 1
                flagged += r.health.diagnosed_fault != "NONE"
        self.assertLessEqual(flagged / total, 0.01, f"{flagged}/{total} nominal samples flagged")

    def test_faults_are_diagnosed_correctly(self):
        """Every fault class, incl. misfire, combustion instability, injector coking and sensor drift."""
        per_class = defaultdict(lambda: [0, 0])
        for run in self.fault_runs().values():
            for i, (r, label, sev, _) in enumerate(run):
                if label != "NONE" and sev >= 0.1 and i >= 3:  # allow the 3-sample rolling window to fill
                    per_class[label][1] += 1
                    per_class[label][0] += r.health.diagnosed_fault == label
        correct = sum(c for c, _ in per_class.values())
        total = sum(n for _, n in per_class.values())
        self.assertGreaterEqual(correct / total, 0.95, f"{correct}/{total} overall")
        for cls, (c, n) in per_class.items():
            self.assertGreaterEqual(c / n, 0.85, f"{cls}: {c}/{n}")

    def test_health_tracks_engine_severity(self):
        """Health = 100 x (1 - engine severity); a drifting sensor leaves engine health ~100."""
        rows = [run[-1] for run in self.fault_runs().values() if run[-1][1] != "NONE"]
        err = sum(abs(r.rul.healthIndexScore - 100 * (1 - eng)) for r, _, _, eng in rows) / len(rows)
        self.assertLess(err, 6.0, f"mean |health - 100(1-engine_severity)| = {err:.2f}")

    def test_sensor_drift_is_not_engine_degradation(self):
        runs = [run for run in self.fault_runs().values() if run[-1][1] == "SENSOR_DRIFT" and run[-1][2] >= 0.3]
        self.assertTrue(runs)
        for run in runs:
            r = run[-1][0]
            self.assertEqual(r.health.diagnosed_fault, "SENSOR_DRIFT")
            self.assertGreaterEqual(r.rul.healthIndexScore, 90.0)
            self.assertEqual(r.maintenance.action, "INSPECTION")
            self.assertIn("SENSORS", r.maintenance.affectedSubsystems)
            self.assertNotEqual(r.health.suspect_sensor, "unidentified")

    def test_stuck_sensor_detected_and_excluded(self):
        """A frozen oil-pressure reading becomes SENSOR_FAILURE; a frozen EGT is replaced from the other cylinders."""
        ep = self.df.loc[self.df["fault_class"] == "NONE", "episode"].iloc[1]
        frozen = {}

        def freeze(i, p):
            frozen.setdefault("op", p["oil_pressure"])
            frozen.setdefault("egt", p["egt"][1])
            if i >= 5:
                p["oil_pressure"] = frozen["op"]
                p["egt"][1] = frozen["egt"]

        run = self.run_episode(HealthRulService(), ep, mutate=freeze)
        last = run[-1][0]
        self.assertEqual(last.health.diagnosed_fault, "SENSOR_FAILURE")
        self.assertIn("oil_pressure", last.data_quality.failed_sensors)
        self.assertIn("egt2", last.data_quality.failed_sensors)
        self.assertGreaterEqual(last.rul.healthIndexScore, 90.0)
        # before the stuck limit is reached nothing is flagged
        self.assertEqual(run[6][0].data_quality.failed_sensors, [])

    def test_stuck_detection_off_for_sandbox(self):
        g = DataQualityGuard()
        frame = {"rpm": 4800, "throttle": 78.5, "egt": [840] * 4, "cht": [106] * 4, "oil_pressure": 3.85, "is_sandbox": True}
        for _ in range(100):
            out = g.validate_and_clean_frame(dict(frame))
        self.assertEqual(out["summary"].failed_sensors, [])

    # ---------------- consistency of derived outputs ----------------
    def test_prognostic_outputs_are_consistent(self):
        ep = self.df.loc[self.df["fault_class"] == "COOLING_DEGRADATION", "episode"].iloc[0]
        for r, *_ in self.run_episode(HealthRulService(), ep):
            p = r.rul
            self.assertAlmostEqual(p.engineDegradationIndex + p.healthIndexScore, 100.0, delta=0.11)
            self.assertLessEqual(p.rulHoursLower95, p.rulHours)
            self.assertLessEqual(p.rulHours, p.rulHoursUpper95)
            risks = [p.multiHorizonRisk[k] for k in ("1hr", "4hr", "8hr", "24hr")]
            self.assertEqual(risks, sorted(risks))
            if r.health.diagnosed_fault not in ("NONE", "SENSOR_DRIFT", "SENSOR_FAILURE"):   # engine faults
                self.assertAlmostEqual(p.degradationRatePercentPerHour, p.healthIndexScore / p.rulHours, delta=0.01 + 0.01 * p.degradationRatePercentPerHour)
                for ev in r.maintenance.evidence:
                    self.assertIsNotNone(ev.nominal_value)
                    self.assertIsNotNone(ev.observed_value)

    def test_golden_twin_parity_with_js(self):
        """Python GoldenTwin must reproduce the JS GoldenTwin used by the gateway."""
        worst = 0.0
        for _, g in self.episodes.items():
            twin = GoldenTwin()
            for _, r in g.iterrows():
                frame = {k: float(r[k]) for k in ("throttle", "rpm", "gen_current")}
                frame.update(ambient_pressure=float(r["ambient_pressure_bar"]), oat=float(r["oat_c"]),
                             battery_current=float(r["battery_current_a"]), battery_soc=float(r["battery_soc_pct"]))
                nom = twin.update(frame, float(r["dt_s"]))
                worst = max(worst, abs(nom["egt"] - r["twin_egt"]), abs(nom["cht"] - r["twin_cht"]),
                            abs(nom["oil_temp"] - r["twin_oil_temp"]), abs(nom["coolant_temp"] - r["twin_coolant"]),
                            abs(nom["inj_pw"] - r["twin_inj_pw"]), abs(nom["gen_voltage"] - r["twin_gen_v"]))
        self.assertLess(worst, 0.05)

    def test_sandbox_payload_format(self):
        """Judges Sandbox sends a different key dialect and no time base."""
        svc = HealthRulService()
        # Cylinder-3 injector clog at 0.85 (simulator steady state, 14,500 ft ISA): the ECU's +15 % trim
        # richens every cylinder, so the others run ~60 °C below nominal while cylinder 3 runs hot
        payload = {"rpm": 4800, "throttle_pct": 78.5, "egt": [777.2, 779.2, 900.3, 778.0], "cht": [105.9, 105.9, 129.7, 106.0],
                   "map_bar": 1.42, "oil_press_bar": 3.85, "oil_temp_c": 98.0, "vibration_grms": 1.10,
                   "gen_voltage_v": 28.4, "fuel_flow": 29.9, "lambda": 0.950, "inj_pw_ms": 16.39, "fuel_trim_pct": 15.0,
                   "altitude_ft": 14500, "is_sandbox": True, "mode": "SANDBOX"}
        for _ in range(3):
            r = svc.predict(dict(payload))
        self.assertEqual(r.health.diagnosed_fault, "CYL3_INJECTOR")
        self.assertIn("SANDBOX", svc.sessions)


if __name__ == "__main__":
    unittest.main()
